# Generated by Django 3.2.8 on 2021-10-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('id',)},
        ),
    ]
